name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: America/New_York
          config_display: regular
          retries: 3
          retries_delay: 300
      - name: Default algorithm (with details)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
      - name: Mildly interesting facts
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.habits.facts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits_days: 30
          config_timezone: America/New_York
      - name: Recently starred
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.stars.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 3
      - name: MBTI Personality profile
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.16personalities.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_16personalities: yes
          plugin_16personalities_url: ${{ secrets.SIXTEEN_PERSONALITIES_URL }}
          plugin_16personalities_sections: personality, profile, traits
          plugin_16personalities_scores: no
      - name: Profile and detailed game history
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.steam.full.svg
          token: NOT_NEEDED
          base: ""
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam: yes
          plugin_steam_user: "0"
      - name: Spotify - Top tracks
        uses: lowlighter/metrics@latest
        with:
          token: NOT_NEEDED
          base: ""
          plugin_music: yes
          plugin_music_mode: top
          plugin_music_provider: spotify
          plugin_music_token: "${{ secrets.SPOTIFY_CLIENT_ID }}, ${{ secrets.SPOTIFY_CLIENT_SECRET }}, ${{ secrets.SPOTIFY_REFRESH_TOKEN }}"
          plugin_music_time_range: short
          plugin_music_top_type: tracks
          plugin_music_playlist: https://open.spotify.com/embed/playlist/2nABVnPyI0Gp7v2t5dOfDu
